import { useState, useEffect, useMemo, useCallback } from "react";
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Area, AreaChart, CartesianGrid, RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis } from "recharts";
import { AlertTriangle, TrendingUp, TrendingDown, Minus, Activity, Zap, BarChart3, Search, ChevronRight, ChevronDown, Clock, Users, MessageSquare, RefreshCw, Plus, X, Filter, Eye, Layers, Bell, Shield, Cpu, ArrowUpRight, ArrowDownRight } from "lucide-react";

// ─── Embedded analysis data (generated by ML pipeline) ───

// ─── Color Palette ───
const COLORS = {
  bg: "#0a0a0f",
  surface: "#12121a",
  surfaceHover: "#1a1a28",
  border: "#1e1e2e",
  borderLight: "#2a2a3e",
  text: "#e4e4ef",
  textMuted: "#8888a0",
  textDim: "#555570",
  accent: "#6366f1",
  accentLight: "#818cf8",
  accentDim: "rgba(99,102,241,0.15)",
  increasing: "#ef4444",
  increasingDim: "rgba(239,68,68,0.12)",
  decreasing: "#22c55e",
  decreasingDim: "rgba(34,197,94,0.12)",
  stable: "#eab308",
  stableDim: "rgba(234,179,8,0.12)",
  critical: "#ef4444",
  high: "#f97316",
  medium: "#eab308",
  low: "#22c55e",
  chartColors: ["#6366f1","#8b5cf6","#a78bfa","#c084fc","#e879f9","#f472b6","#fb7185","#f87171","#fb923c","#fbbf24","#a3e635","#34d399","#2dd4bf","#22d3ee","#38bdf8","#60a5fa","#818cf8","#a78bfa","#c4b5fd","#e0e7ff"],
};

const PRIORITY_COLORS = { Critical: COLORS.critical, High: COLORS.high, Medium: COLORS.medium, Low: COLORS.low };

// ─── Utility Components ───

const TrendIcon = ({ trend, size = 16 }) => {
  if (trend === "increasing") return <TrendingUp size={size} style={{ color: COLORS.increasing }} />;
  if (trend === "decreasing") return <TrendingDown size={size} style={{ color: COLORS.decreasing }} />;
  return <Minus size={size} style={{ color: COLORS.stable }} />;
};

const TrendBadge = ({ trend, pctChange }) => {
  const colors = {
    increasing: { bg: COLORS.increasingDim, text: COLORS.increasing, border: "rgba(239,68,68,0.3)" },
    decreasing: { bg: COLORS.decreasingDim, text: COLORS.decreasing, border: "rgba(34,197,94,0.3)" },
    stable: { bg: COLORS.stableDim, text: COLORS.stable, border: "rgba(234,179,8,0.3)" },
  };
  const c = colors[trend] || colors.stable;
  const label = trend === "increasing" ? "Rising" : trend === "decreasing" ? "Falling" : "Stable";
  return (
    <span style={{
      display: "inline-flex", alignItems: "center", gap: 4,
      padding: "3px 10px", borderRadius: 20, fontSize: 11, fontWeight: 600,
      background: c.bg, color: c.text, border: `1px solid ${c.border}`,
      letterSpacing: "0.03em", textTransform: "uppercase",
    }}>
      <TrendIcon trend={trend} size={12} />
      {label} {pctChange != null && `${pctChange > 0 ? "+" : ""}${pctChange}%`}
    </span>
  );
};

const PriorityBadge = ({ priority }) => {
  const color = PRIORITY_COLORS[priority] || COLORS.textMuted;
  return (
    <span style={{
      display: "inline-flex", alignItems: "center", gap: 4,
      padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 600,
      background: `${color}18`, color: color, border: `1px solid ${color}30`,
      textTransform: "uppercase", letterSpacing: "0.05em",
    }}>
      <span style={{ width: 5, height: 5, borderRadius: "50%", background: color }} />
      {priority}
    </span>
  );
};

const MiniSparkline = ({ data, trend, width = 120, height = 32 }) => {
  const color = trend === "increasing" ? COLORS.increasing : trend === "decreasing" ? COLORS.decreasing : COLORS.stable;
  return (
    <ResponsiveContainer width={width} height={height}>
      <AreaChart data={data} margin={{ top: 2, right: 2, bottom: 2, left: 2 }}>
        <defs>
          <linearGradient id={`spark-${trend}`} x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={color} stopOpacity={0.3} />
            <stop offset="100%" stopColor={color} stopOpacity={0} />
          </linearGradient>
        </defs>
        <Area type="monotone" dataKey="count" stroke={color} fill={`url(#spark-${trend})`} strokeWidth={1.5} dot={false} />
      </AreaChart>
    </ResponsiveContainer>
  );
};

const StatCard = ({ icon: Icon, label, value, sub, color = COLORS.accent }) => (
  <div style={{
    background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 12,
    padding: "20px 22px", display: "flex", flexDirection: "column", gap: 10,
    position: "relative", overflow: "hidden",
  }}>
    <div style={{ position: "absolute", top: -20, right: -20, width: 80, height: 80, borderRadius: "50%", background: `${color}08` }} />
    <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
      <div style={{ width: 36, height: 36, borderRadius: 8, background: `${color}15`, display: "flex", alignItems: "center", justifyContent: "center" }}>
        <Icon size={18} style={{ color }} />
      </div>
      <span style={{ fontSize: 12, color: COLORS.textMuted, fontWeight: 500, textTransform: "uppercase", letterSpacing: "0.06em" }}>{label}</span>
    </div>
    <div style={{ fontSize: 28, fontWeight: 700, color: COLORS.text, fontFamily: "'JetBrains Mono', monospace" }}>{value}</div>
    {sub && <div style={{ fontSize: 11, color: COLORS.textDim }}>{sub}</div>}
  </div>
);

// ─── Cluster Detail Panel ───

const ClusterDetail = ({ cluster, onClose, onCloseTicket }) => {
  const [ticketPage, setTicketPage] = useState(0);
  const [ticketSearch, setTicketSearch] = useState("");
  const [sortOrder, setSortOrder] = useState("newest");
  const TICKETS_PER_PAGE = 15;

  if (!cluster) return null;

  const priorityData = Object.entries(cluster.priority || {}).map(([name, value]) => ({ name, value }));
  const channelData = Object.entries(cluster.channels || {}).map(([name, value]) => ({ name, value }));

  const allTickets = cluster.tickets || cluster.examples || [];

  const processedTickets = (() => {
    let t = [...allTickets];
    if (ticketSearch) {
      const q = ticketSearch.toLowerCase();
      t = t.filter(tk =>
        tk.subject?.toLowerCase().includes(q) ||
        tk.description?.toLowerCase().includes(q) ||
        tk.product?.toLowerCase().includes(q) ||
        tk.ticket_id?.toString().includes(q)
      );
    }
    if (sortOrder === "oldest") t.reverse();
    return t;
  })();

  const totalPages = Math.ceil(processedTickets.length / TICKETS_PER_PAGE);
  const pageTickets = processedTickets.slice(ticketPage * TICKETS_PER_PAGE, (ticketPage + 1) * TICKETS_PER_PAGE);

  const groupedByDate = (() => {
    const groups = [];
    let currentDate = null;
    for (const ticket of pageTickets) {
      const d = ticket.date || "Unknown";
      if (d !== currentDate) {
        currentDate = d;
        groups.push({ date: d, tickets: [ticket] });
      } else {
        groups[groups.length - 1].tickets.push(ticket);
      }
    }
    return groups;
  })();

  const handleSearchChange = (val) => {
    setTicketSearch(val);
    setTicketPage(0);
  };

  return (
    <div style={{
      position: "fixed", top: 0, right: 0, bottom: 0, width: "min(600px, 90vw)",
      background: COLORS.surface, borderLeft: `1px solid ${COLORS.border}`,
      zIndex: 1000, overflowY: "auto", boxShadow: "-20px 0 60px rgba(0,0,0,0.5)",
    }}>
      {/* Header */}
      <div style={{
        position: "sticky", top: 0, background: COLORS.surface, borderBottom: `1px solid ${COLORS.border}`,
        padding: "20px 24px", display: "flex", justifyContent: "space-between", alignItems: "flex-start",
        zIndex: 10, backdropFilter: "blur(10px)",
      }}>
        <div>
          <div style={{ fontSize: 11, color: COLORS.textMuted, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 6 }}>Issue Cluster #{cluster.id}</div>
          <h2 style={{ fontSize: 22, fontWeight: 700, color: COLORS.text, margin: 0 }}>{cluster.name}</h2>
          <div style={{ marginTop: 8, display: "flex", gap: 8 }}>
            <TrendBadge trend={cluster.trend} pctChange={cluster.pct_change} />
            <span style={{ fontSize: 12, color: COLORS.textMuted, display: "flex", alignItems: "center", gap: 4 }}>
              <MessageSquare size={12} /> {cluster.count} tickets
            </span>
          </div>
        </div>
        <button onClick={onClose} style={{
          background: "none", border: `1px solid ${COLORS.border}`, borderRadius: 8,
          color: COLORS.textMuted, cursor: "pointer", padding: 8, display: "flex",
        }}>
          <X size={16} />
        </button>
      </div>

      <div style={{ padding: "20px 24px", display: "flex", flexDirection: "column", gap: 24 }}>
        {/* Trend Chart */}
        <div>
          <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: "0 0 12px", textTransform: "uppercase", letterSpacing: "0.06em" }}>Volume Over Time</h3>
          <div style={{ background: COLORS.bg, borderRadius: 10, padding: "16px 8px 8px", border: `1px solid ${COLORS.border}` }}>
            <ResponsiveContainer width="100%" height={180}>
              <AreaChart data={cluster.time_series}>
                <defs>
                  <linearGradient id="detailGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor={COLORS.accent} stopOpacity={0.25} />
                    <stop offset="100%" stopColor={COLORS.accent} stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke={COLORS.border} />
                <XAxis dataKey="month" tick={{ fill: COLORS.textDim, fontSize: 10 }} tickLine={false} axisLine={false} interval={2} />
                <YAxis tick={{ fill: COLORS.textDim, fontSize: 10 }} tickLine={false} axisLine={false} width={30} />
                <Tooltip
                  contentStyle={{ background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 8, fontSize: 12 }}
                  labelStyle={{ color: COLORS.textMuted }}
                  itemStyle={{ color: COLORS.accent }}
                />
                <Area type="monotone" dataKey="count" stroke={COLORS.accent} fill="url(#detailGrad)" strokeWidth={2} dot={false} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
          <div style={{ display: "flex", gap: 16, marginTop: 12 }}>
            <div style={{ flex: 1, background: COLORS.bg, borderRadius: 8, padding: "12px 16px", border: `1px solid ${COLORS.border}` }}>
              <div style={{ fontSize: 10, color: COLORS.textDim, marginBottom: 4 }}>Previous Window</div>
              <div style={{ fontSize: 20, fontWeight: 700, color: COLORS.text, fontFamily: "'JetBrains Mono', monospace" }}>{cluster.prev_window}</div>
            </div>
            <div style={{ flex: 1, background: COLORS.bg, borderRadius: 8, padding: "12px 16px", border: `1px solid ${COLORS.border}` }}>
              <div style={{ fontSize: 10, color: COLORS.textDim, marginBottom: 4 }}>Current Window</div>
              <div style={{ fontSize: 20, fontWeight: 700, color: COLORS.text, fontFamily: "'JetBrains Mono', monospace" }}>{cluster.curr_window}</div>
            </div>
          </div>
        </div>

        {/* Key Signals */}
        <div>
          <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: "0 0 12px", textTransform: "uppercase", letterSpacing: "0.06em" }}>Key Signals</h3>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
            {cluster.top_terms?.map((term, i) => (
              <span key={i} style={{
                padding: "4px 10px", borderRadius: 6, fontSize: 11, fontWeight: 500,
                background: i < 3 ? COLORS.accentDim : COLORS.bg,
                color: i < 3 ? COLORS.accentLight : COLORS.textMuted,
                border: `1px solid ${i < 3 ? "rgba(99,102,241,0.3)" : COLORS.border}`,
              }}>{term}</span>
            ))}
          </div>
        </div>

        {/* Priority & Channels */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
          <div>
            <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: "0 0 12px", textTransform: "uppercase", letterSpacing: "0.06em" }}>Priority Split</h3>
            <div style={{ background: COLORS.bg, borderRadius: 10, padding: 16, border: `1px solid ${COLORS.border}` }}>
              {priorityData.map(({ name, value }) => (
                <div key={name} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 0" }}>
                  <PriorityBadge priority={name} />
                  <span style={{ fontSize: 13, fontWeight: 600, color: COLORS.text, fontFamily: "'JetBrains Mono', monospace" }}>{value}</span>
                </div>
              ))}
            </div>
          </div>
          <div>
            <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: "0 0 12px", textTransform: "uppercase", letterSpacing: "0.06em" }}>Channels</h3>
            <div style={{ background: COLORS.bg, borderRadius: 10, padding: 16, border: `1px solid ${COLORS.border}` }}>
              {channelData.map(({ name, value }) => (
                <div key={name} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 0" }}>
                  <span style={{ fontSize: 12, color: COLORS.textMuted }}>{name}</span>
                  <span style={{ fontSize: 13, fontWeight: 600, color: COLORS.text, fontFamily: "'JetBrains Mono', monospace" }}>{value}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Resolution Stats */}
        {cluster.resolution && (
          <div>
            <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: "0 0 12px", textTransform: "uppercase", letterSpacing: "0.06em" }}>Resolution Metrics</h3>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10 }}>
              <div style={{ background: COLORS.bg, borderRadius: 8, padding: "12px", border: `1px solid ${COLORS.border}`, textAlign: "center" }}>
                <div style={{ fontSize: 10, color: COLORS.textDim, marginBottom: 4 }}>Avg Resolution</div>
                <div style={{ fontSize: 16, fontWeight: 700, color: COLORS.text, fontFamily: "'JetBrains Mono', monospace" }}>{cluster.resolution.avg_resolution_hours || "N/A"}h</div>
              </div>
              <div style={{ background: COLORS.bg, borderRadius: 8, padding: "12px", border: `1px solid ${COLORS.border}`, textAlign: "center" }}>
                <div style={{ fontSize: 10, color: COLORS.textDim, marginBottom: 4 }}>Satisfaction</div>
                <div style={{ fontSize: 16, fontWeight: 700, color: COLORS.text, fontFamily: "'JetBrains Mono', monospace" }}>{cluster.resolution.avg_satisfaction || "N/A"}/5</div>
              </div>
              <div style={{ background: COLORS.bg, borderRadius: 8, padding: "12px", border: `1px solid ${COLORS.border}`, textAlign: "center" }}>
                <div style={{ fontSize: 10, color: COLORS.textDim, marginBottom: 4 }}>Open</div>
                <div style={{ fontSize: 16, fontWeight: 700, color: COLORS.increasing, fontFamily: "'JetBrains Mono', monospace" }}>{cluster.resolution.open_tickets}</div>
              </div>
            </div>
          </div>
        )}

        {/* Affected Products */}
        {cluster.top_products?.length > 0 && (
          <div>
            <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: "0 0 12px", textTransform: "uppercase", letterSpacing: "0.06em" }}>Top Affected Products</h3>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
              {cluster.top_products.map((p, i) => (
                <span key={i} style={{
                  padding: "5px 12px", borderRadius: 6, fontSize: 12,
                  background: COLORS.bg, color: COLORS.text,
                  border: `1px solid ${COLORS.border}`,
                }}>{p}</span>
              ))}
            </div>
          </div>
        )}

        {/* Ticket Timeline — All tickets sorted by arrival time */}
        <div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12, flexWrap: "wrap", gap: 8 }}>
            <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: 0, textTransform: "uppercase", letterSpacing: "0.06em" }}>
              Tickets ({processedTickets.length})
            </h3>
            <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
              <div style={{
                display: "flex", alignItems: "center", gap: 6, padding: "6px 10px",
                background: COLORS.bg, borderRadius: 6, border: `1px solid ${COLORS.border}`, width: 180,
              }}>
                <Search size={12} style={{ color: COLORS.textDim, flexShrink: 0 }} />
                <input
                  placeholder="Filter tickets..."
                  value={ticketSearch}
                  onChange={e => handleSearchChange(e.target.value)}
                  style={{ background: "none", border: "none", outline: "none", color: COLORS.text, fontSize: 11, width: "100%" }}
                />
              </div>
              <button
                onClick={() => { setSortOrder(s => s === "newest" ? "oldest" : "newest"); setTicketPage(0); }}
                style={{
                  padding: "6px 10px", borderRadius: 6, border: `1px solid ${COLORS.border}`,
                  background: COLORS.bg, color: COLORS.textMuted, cursor: "pointer",
                  fontSize: 10, fontWeight: 600, display: "flex", alignItems: "center", gap: 4,
                }}
              >
                <Clock size={11} />
                {sortOrder === "newest" ? "Newest First" : "Oldest First"}
              </button>
            </div>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {groupedByDate.map((group, gi) => (
              <div key={gi}>
                <div style={{
                  display: "flex", alignItems: "center", gap: 10, padding: "10px 0 6px",
                  position: "sticky", top: 72, zIndex: 5, background: COLORS.surface,
                }}>
                  <div style={{
                    width: 8, height: 8, borderRadius: "50%", background: COLORS.accent,
                    boxShadow: `0 0 6px ${COLORS.accent}60`, flexShrink: 0,
                  }} />
                  <div style={{
                    fontSize: 11, fontWeight: 700, color: COLORS.accentLight,
                    fontFamily: "'JetBrains Mono', monospace", letterSpacing: "0.04em",
                  }}>{group.date}</div>
                  <div style={{ flex: 1, height: 1, background: COLORS.border }} />
                  <span style={{ fontSize: 10, color: COLORS.textDim }}>{group.tickets.length} ticket{group.tickets.length !== 1 ? "s" : ""}</span>
                </div>

                <div style={{ display: "flex", flexDirection: "column", gap: 6, paddingLeft: 18, borderLeft: `2px solid ${COLORS.border}`, marginLeft: 3 }}>
                  {group.tickets.map((ticket, ti) => (
                    <div key={ti} style={{
                      background: COLORS.bg, borderRadius: 10, padding: "12px 14px",
                      border: `1px solid ${ticket.status === "Closed" ? "rgba(34,197,94,0.2)" : COLORS.border}`, position: "relative",
                      transition: "all 0.15s",
                      opacity: ticket.status === "Closed" ? 0.6 : 1,
                    }}
                      onMouseEnter={e => e.currentTarget.style.borderColor = COLORS.borderLight}
                      onMouseLeave={e => e.currentTarget.style.borderColor = COLORS.border}
                    >
                      <div style={{
                        position: "absolute", left: -23, top: 16,
                        width: 6, height: 6, borderRadius: "50%",
                        background: COLORS.surface, border: `2px solid ${COLORS.borderLight}`,
                      }} />
                      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 }}>
                        <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
                          <span style={{ fontSize: 10, color: COLORS.textDim, fontFamily: "'JetBrains Mono', monospace" }}>#{ticket.ticket_id}</span>
                          <span style={{ fontSize: 12, fontWeight: 600, color: COLORS.text }}>{ticket.subject}</span>
                          <span style={{
                            fontSize: 9, padding: "1px 6px", borderRadius: 3,
                            background: `${COLORS.accent}12`, color: COLORS.accentLight,
                            border: `1px solid ${COLORS.accent}25`,
                          }}>{ticket.type}</span>
                        </div>
                        <PriorityBadge priority={ticket.priority} />
                      </div>
                      <p style={{ fontSize: 11, color: COLORS.textMuted, margin: "0 0 6px", lineHeight: 1.5 }}>
                        {ticket.description?.slice(0, 140)}{ticket.description?.length > 140 ? "..." : ""}
                      </p>
                      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 6 }}>
                        <div style={{ display: "flex", gap: 10, fontSize: 10, color: COLORS.textDim, flexWrap: "wrap", alignItems: "center" }}>
                          <span>{ticket.product}</span>
                          <span>{ticket.channel}</span>
                          <span style={{
                            color: ticket.status === "Open" ? COLORS.increasing : ticket.status === "Closed" ? COLORS.decreasing : COLORS.stable,
                            fontWeight: 600,
                          }}>{ticket.status}</span>
                        </div>
                        {ticket.status !== "Closed" && (
                          <button
                            onClick={(e) => { e.stopPropagation(); onCloseTicket(ticket.ticket_id, cluster.id); }}
                            style={{
                              padding: "3px 10px", borderRadius: 5, fontSize: 10, fontWeight: 600,
                              background: "rgba(34,197,94,0.1)", color: COLORS.decreasing,
                              border: `1px solid rgba(34,197,94,0.25)`, cursor: "pointer",
                              display: "flex", alignItems: "center", gap: 4,
                              transition: "all 0.15s",
                            }}
                            onMouseEnter={e => { e.currentTarget.style.background = "rgba(34,197,94,0.2)"; }}
                            onMouseLeave={e => { e.currentTarget.style.background = "rgba(34,197,94,0.1)"; }}
                          >
                            <X size={10} /> Close Ticket
                          </button>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          {totalPages > 1 && (
            <div style={{
              display: "flex", justifyContent: "center", alignItems: "center", gap: 8,
              marginTop: 16, padding: "12px 0",
            }}>
              <button
                onClick={() => setTicketPage(p => Math.max(0, p - 1))}
                disabled={ticketPage === 0}
                style={{
                  padding: "6px 14px", borderRadius: 6, border: `1px solid ${COLORS.border}`,
                  background: COLORS.bg, color: ticketPage === 0 ? COLORS.textDim : COLORS.text,
                  cursor: ticketPage === 0 ? "default" : "pointer", fontSize: 11, fontWeight: 600,
                  opacity: ticketPage === 0 ? 0.4 : 1,
                }}
              >← Prev</button>
              <div style={{ display: "flex", gap: 3 }}>
                {Array.from({ length: Math.min(totalPages, 7) }, (_, i) => {
                  let page;
                  if (totalPages <= 7) page = i;
                  else if (ticketPage < 4) page = i;
                  else if (ticketPage > totalPages - 5) page = totalPages - 7 + i;
                  else page = ticketPage - 3 + i;
                  return (
                    <button key={page} onClick={() => setTicketPage(page)} style={{
                      width: 28, height: 28, borderRadius: 6, border: "none",
                      background: page === ticketPage ? COLORS.accent : "transparent",
                      color: page === ticketPage ? "white" : COLORS.textDim,
                      cursor: "pointer", fontSize: 11, fontWeight: 600,
                    }}>{page + 1}</button>
                  );
                })}
              </div>
              <button
                onClick={() => setTicketPage(p => Math.min(totalPages - 1, p + 1))}
                disabled={ticketPage === totalPages - 1}
                style={{
                  padding: "6px 14px", borderRadius: 6, border: `1px solid ${COLORS.border}`,
                  background: COLORS.bg, color: ticketPage === totalPages - 1 ? COLORS.textDim : COLORS.text,
                  cursor: ticketPage === totalPages - 1 ? "default" : "pointer", fontSize: 11, fontWeight: 600,
                  opacity: ticketPage === totalPages - 1 ? 0.4 : 1,
                }}
              >Next →</button>
              <span style={{ fontSize: 10, color: COLORS.textDim, marginLeft: 8 }}>
                {ticketPage * TICKETS_PER_PAGE + 1}–{Math.min((ticketPage + 1) * TICKETS_PER_PAGE, processedTickets.length)} of {processedTickets.length}
              </span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// ─── Ingest Modal ───

const IngestModal = ({ onClose, onSubmit }) => {
  const [form, setForm] = useState({
    subject: "Network problem", description: "", product: "iPhone 15",
    type: "Technical issue", priority: "Medium", channel: "Email",
  });

  return (
    <div style={{
      position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", zIndex: 1000,
      display: "flex", alignItems: "center", justifyContent: "center", backdropFilter: "blur(4px)",
    }} onClick={onClose}>
      <div style={{
        background: COLORS.surface, borderRadius: 16, border: `1px solid ${COLORS.border}`,
        padding: 28, width: "min(480px, 90vw)", boxShadow: "0 20px 60px rgba(0,0,0,0.4)",
      }} onClick={e => e.stopPropagation()}>
        <h2 style={{ fontSize: 18, fontWeight: 700, color: COLORS.text, margin: "0 0 20px" }}>Ingest New Ticket</h2>
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          {[
            { label: "Subject", key: "subject", options: ["Network problem","Software bug","Payment issue","Battery life","Hardware issue","Account access","Data loss","Display issue","Refund request","Delivery problem"] },
            { label: "Product", key: "product", options: ["iPhone 15","MacBook Pro","Samsung Galaxy","Dell XPS","Sony PlayStation","iPad Pro","Google Pixel","Nintendo Switch"] },
            { label: "Type", key: "type", options: ["Technical issue","Billing inquiry","Product inquiry","Refund request","Cancellation request"] },
            { label: "Priority", key: "priority", options: ["Low","Medium","High","Critical"] },
            { label: "Channel", key: "channel", options: ["Email","Phone","Chat","Social media"] },
          ].map(({ label, key, options }) => (
            <div key={key}>
              <label style={{ fontSize: 11, color: COLORS.textMuted, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.06em" }}>{label}</label>
              <select value={form[key]} onChange={e => setForm(f => ({ ...f, [key]: e.target.value }))}
                style={{
                  width: "100%", marginTop: 4, padding: "10px 12px", borderRadius: 8,
                  background: COLORS.bg, border: `1px solid ${COLORS.border}`,
                  color: COLORS.text, fontSize: 13, outline: "none",
                }}>
                {options.map(o => <option key={o} value={o}>{o}</option>)}
              </select>
            </div>
          ))}
          <div>
            <label style={{ fontSize: 11, color: COLORS.textMuted, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.06em" }}>Description</label>
            <textarea value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))}
              placeholder="Describe the issue..."
              rows={3}
              style={{
                width: "100%", marginTop: 4, padding: "10px 12px", borderRadius: 8,
                background: COLORS.bg, border: `1px solid ${COLORS.border}`,
                color: COLORS.text, fontSize: 13, outline: "none", resize: "vertical",
                fontFamily: "inherit",
              }} />
          </div>
        </div>
        <div style={{ display: "flex", gap: 10, marginTop: 20, justifyContent: "flex-end" }}>
          <button onClick={onClose} style={{
            padding: "10px 20px", borderRadius: 8, background: "none", border: `1px solid ${COLORS.border}`,
            color: COLORS.textMuted, cursor: "pointer", fontSize: 13, fontWeight: 600,
          }}>Cancel</button>
          <button onClick={() => { onSubmit(form); onClose(); }} style={{
            padding: "10px 20px", borderRadius: 8, background: COLORS.accent, border: "none",
            color: "white", cursor: "pointer", fontSize: 13, fontWeight: 600,
          }}>Submit Ticket</button>
        </div>
      </div>
    </div>
  );
};

// ─── Main Dashboard ───

export default function SupportIntelligenceDashboard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedCluster, setSelectedCluster] = useState(null);
  const [filter, setFilter] = useState("all"); // all, increasing, decreasing, stable
  const [searchQuery, setSearchQuery] = useState("");
  const [showIngest, setShowIngest] = useState(false);
  const [simulating, setSimulating] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [view, setView] = useState("clusters"); // clusters, trends, anomalies
  const [toast, setToast] = useState(null); // { message, type }

  const showToast = (message, type = "success") => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 3000);
  };

  // Load embedded data or fetch from API
 const loadData = async () => {

  setLoading(true);

  try {

    const res = await fetch("/api/analysis");

    if (!res.ok) {
      throw new Error("API error");
    }

    const json = await res.json();

    setData(json);

  } catch (err) {

    console.error("Failed to load analysis:", err);

  }

  setLoading(false);
};

useEffect(() => {
  loadData();
}, []);

  const handleSimulate = async (count = 20) => {
    setSimulating(true);

    // Local state update: generate synthetic tickets across random clusters
    const subjects = ['Network problem', 'Software bug', 'Payment issue', 'Battery life',
                      'Hardware issue', 'Account access', 'Data loss', 'Display issue'];
    const products = ['iPhone 15', 'Samsung Galaxy S24', 'MacBook Pro', 'Dell XPS',
                      'Sony PlayStation', 'Nintendo Switch', 'iPad Pro', 'Google Pixel'];
    const types = ['Technical issue', 'Billing inquiry', 'Product inquiry', 'Refund request'];
    const priorities = ['Low', 'Medium', 'High', 'Critical'];
    const channels = ['Email', 'Phone', 'Chat', 'Social media'];
    const descs = [
      "Device keeps disconnecting from wifi. Very frustrating.",
      "Charged twice for subscription. Need refund.",
      "App crashes every time I open settings.",
      "Battery drains within 2 hours of full charge.",
      "Screen flickering after the latest update.",
      "Cannot login to account. Password reset not working.",
      "Lost all saved data after system update.",
      "Product arrived damaged. Need replacement.",
      "Bluetooth connectivity keeps dropping.",
      "Software extremely slow after recent patch.",
    ];
    const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
    const today = new Date().toISOString().split('T')[0];

    setData(prev => {
      if (!prev) return prev;
      const updated = JSON.parse(JSON.stringify(prev));
      for (let i = 0; i < count; i++) {
        const newTicket = {
          ticket_id: Math.floor(Math.random() * 90000) + 10000,
          subject: pick(subjects), description: pick(descs),
          product: pick(products), priority: pick(priorities),
          date: today, status: 'Open', type: pick(types), channel: pick(channels),
        };
        // Distribute across a random cluster
        const cluster = updated.clusters[Math.floor(Math.random() * updated.clusters.length)];
        if (!cluster.tickets) cluster.tickets = [];
        cluster.tickets.unshift(newTicket);
        cluster.count += 1;
      }
      updated.global_stats.total_tickets += count;
      updated.global_stats.open_tickets += count;
      return updated;
    });

    // Also send to backend
    try {
      await fetch("/api/simulate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ count }) });
    } catch (e) {}
    setSimulating(false);
    showToast(`Simulated ${count} new tickets — UI updated`);
  };

  const handleRefresh = async () => {
    setRefreshing(true);
    try {
      await fetch("/api/refresh", { method: "POST" });
      await loadData(true);
      showToast("Analysis refreshed from backend");
    } catch (e) {
      showToast("Backend unavailable — showing local data", "warning");
    }
    setRefreshing(false);
  };

  const handleIngest = async (ticket) => {
    // 1. Immediately add to local state so UI updates instantly
    if (data) {
      const newTicket = {
        ticket_id: Math.floor(Math.random() * 90000) + 10000,
        subject: ticket.subject,
        description: ticket.description || '',
        product: ticket.product,
        priority: ticket.priority,
        date: new Date().toISOString().split('T')[0],
        status: 'Open',
        type: ticket.type,
        channel: ticket.channel,
      };

      setData(prev => {
        if (!prev) return prev;
        const updated = JSON.parse(JSON.stringify(prev));

        // Add ticket to the most relevant cluster (best match by subject)
        let bestCluster = updated.clusters[0];
        for (const c of updated.clusters) {
          if (c.name.toLowerCase().includes(ticket.subject.toLowerCase().split(' ')[0]) ||
              ticket.subject.toLowerCase().includes(c.name.toLowerCase().split(' ')[0])) {
            bestCluster = c;
            break;
          }
        }

        // Prepend to tickets array (newest first)
        if (!bestCluster.tickets) bestCluster.tickets = [];
        bestCluster.tickets.unshift(newTicket);
        bestCluster.count += 1;

        // Update global stats
        updated.global_stats.total_tickets += 1;
        updated.global_stats.open_tickets += 1;

        return updated;
      });

      showToast(`Ticket ingested → assigned to cluster`);
    }

    // 2. Also send to backend API
    try {
      await fetch("/api/ingest", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(ticket) });
    } catch (e) {}
  };

  const handleCloseTicket = (ticketId, clusterId) => {
    setData(prev => {
      if (!prev) return prev;
      const updated = JSON.parse(JSON.stringify(prev));

      for (const cluster of updated.clusters) {
        if (cluster.id === clusterId) {
          const ticket = cluster.tickets?.find(t => t.ticket_id === ticketId);
          if (ticket && ticket.status !== "Closed") {
            const wasOpen = ticket.status === "Open";
            ticket.status = "Closed";

            // Update resolution stats
            if (cluster.resolution) {
              cluster.resolution.closed_tickets = (cluster.resolution.closed_tickets || 0) + 1;
              if (wasOpen) {
                cluster.resolution.open_tickets = Math.max(0, (cluster.resolution.open_tickets || 0) - 1);
              } else {
                cluster.resolution.pending_tickets = Math.max(0, (cluster.resolution.pending_tickets || 0) - 1);
              }
            }

            // Update global open count
            if (wasOpen) {
              updated.global_stats.open_tickets = Math.max(0, updated.global_stats.open_tickets - 1);
            }
          }
          break;
        }
      }

      // Also update selectedCluster if it's the same one
      return updated;
    });

    // Update selectedCluster in-place so the panel reflects the change without re-opening
    setSelectedCluster(prev => {
      if (!prev || prev.id !== clusterId) return prev;
      const updatedCluster = JSON.parse(JSON.stringify(prev));
      const ticket = updatedCluster.tickets?.find(t => t.ticket_id === ticketId);
      if (ticket) {
        const wasOpen = ticket.status === "Open";
        ticket.status = "Closed";
        if (updatedCluster.resolution) {
          updatedCluster.resolution.closed_tickets = (updatedCluster.resolution.closed_tickets || 0) + 1;
          if (wasOpen) {
            updatedCluster.resolution.open_tickets = Math.max(0, (updatedCluster.resolution.open_tickets || 0) - 1);
          } else {
            updatedCluster.resolution.pending_tickets = Math.max(0, (updatedCluster.resolution.pending_tickets || 0) - 1);
          }
        }
      }
      return updatedCluster;
    });

    showToast(`Ticket #${ticketId} closed`);

    // Also send to backend
    try {
      fetch("/api/close-ticket", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticket_id: ticketId, cluster_id: clusterId }) });
    } catch (e) {}
  };

  const filteredClusters = useMemo(() => {
    if (!data) return [];
    let clusters = data.clusters || [];
    if (filter !== "all") clusters = clusters.filter(c => c.trend === filter);
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      clusters = clusters.filter(c =>
        c.name.toLowerCase().includes(q) ||
        c.top_terms?.some(t => t.includes(q)) ||
        c.top_products?.some(p => p.toLowerCase().includes(q))
      );
    }
    return clusters;
  }, [data, filter, searchQuery]);

  if (loading) {
    return (
      <div style={{
        minHeight: "100vh", background: COLORS.bg, display: "flex", alignItems: "center", justifyContent: "center",
        fontFamily: "'JetBrains Mono', monospace",
      }}>
        <div style={{ textAlign: "center" }}>
          <div style={{
            width: 48, height: 48, border: `3px solid ${COLORS.border}`, borderTopColor: COLORS.accent,
            borderRadius: "50%", animation: "spin 1s linear infinite", margin: "0 auto 16px",
          }} />
          <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
          <div style={{ color: COLORS.textMuted, fontSize: 14 }}>Analyzing support tickets...</div>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div style={{
        minHeight: "100vh", background: COLORS.bg, display: "flex", alignItems: "center", justifyContent: "center",
        fontFamily: "system-ui, sans-serif", color: COLORS.text, flexDirection: "column", gap: 16,
      }}>
        <AlertTriangle size={48} style={{ color: COLORS.stable }} />
        <div style={{ fontSize: 18, fontWeight: 600 }}>No analysis data available</div>
        <div style={{ fontSize: 14, color: COLORS.textMuted }}>Start the backend server or provide analysis_results.json</div>
      </div>
    );
  }

  const stats = data.global_stats;
  const anomalies = data.anomalies || [];

  return (
    <div style={{
      minHeight: "100vh", background: COLORS.bg, color: COLORS.text,
      fontFamily: "'Satoshi', 'DM Sans', system-ui, -apple-system, sans-serif",
    }}>
      <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700&display=swap" rel="stylesheet" />
      <style>{`
        * { box-sizing: border-box; margin: 0; padding: 0; }
        ::-webkit-scrollbar { width: 6px; }
        ::-webkit-scrollbar-track { background: ${COLORS.bg}; }
        ::-webkit-scrollbar-thumb { background: ${COLORS.border}; border-radius: 3px; }
        ::-webkit-scrollbar-thumb:hover { background: ${COLORS.borderLight}; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
      `}</style>

      {/* ─── Header ─── */}
      <header style={{
        borderBottom: `1px solid ${COLORS.border}`, padding: "16px 32px",
        display: "flex", justifyContent: "space-between", alignItems: "center",
        background: `${COLORS.surface}cc`, backdropFilter: "blur(12px)",
        position: "sticky", top: 0, zIndex: 100,
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
          <div style={{
            width: 38, height: 38, borderRadius: 10, background: `linear-gradient(135deg, ${COLORS.accent}, #a855f7)`,
            display: "flex", alignItems: "center", justifyContent: "center", boxShadow: `0 4px 12px ${COLORS.accent}40`,
          }}>
            <Cpu size={20} color="white" />
          </div>
          <div>
            <h1 style={{ fontSize: 17, fontWeight: 700, letterSpacing: "-0.02em" }}>
              Support Intelligence
            </h1>
            <span style={{ fontSize: 11, color: COLORS.textDim }}>
              ML-powered issue detection &bull; {stats.total_tickets.toLocaleString()} tickets analyzed
            </span>
          </div>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button onClick={() => setShowIngest(true)} style={{
            padding: "8px 16px", borderRadius: 8, background: "none", border: `1px solid ${COLORS.border}`,
            color: COLORS.textMuted, cursor: "pointer", fontSize: 12, fontWeight: 600,
            display: "flex", alignItems: "center", gap: 6, transition: "all 0.15s",
          }}
            onMouseEnter={e => { e.target.style.borderColor = COLORS.accent; e.target.style.color = COLORS.accent; }}
            onMouseLeave={e => { e.target.style.borderColor = COLORS.border; e.target.style.color = COLORS.textMuted; }}
          >
            <Plus size={14} /> Ingest
          </button>
          <button onClick={() => handleSimulate(20)} disabled={simulating} style={{
            padding: "8px 16px", borderRadius: 8, background: "none", border: `1px solid ${COLORS.border}`,
            color: COLORS.textMuted, cursor: "pointer", fontSize: 12, fontWeight: 600,
            display: "flex", alignItems: "center", gap: 6, opacity: simulating ? 0.5 : 1,
          }}>
            <Zap size={14} /> {simulating ? "Simulating..." : "Simulate +20"}
          </button>
          <button onClick={handleRefresh} disabled={refreshing} style={{
            padding: "8px 16px", borderRadius: 8, background: COLORS.accent, border: "none",
            color: "white", cursor: "pointer", fontSize: 12, fontWeight: 600,
            display: "flex", alignItems: "center", gap: 6, opacity: refreshing ? 0.5 : 1,
          }}>
            <RefreshCw size={14} style={{ animation: refreshing ? "spin 1s linear infinite" : "none" }} />
            {refreshing ? "Analyzing..." : "Refresh Analysis"}
          </button>
        </div>
      </header>

      <main style={{ padding: "24px 32px", maxWidth: 1440, margin: "0 auto" }}>
        {/* ─── Stat Cards ─── */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 14, marginBottom: 28 }}>
          <StatCard icon={Layers} label="Total Tickets" value={stats.total_tickets.toLocaleString()} sub={`${stats.date_range.start} → ${stats.date_range.end}`} />
          <StatCard icon={Activity} label="Issue Clusters" value={stats.total_clusters} sub={`${stats.increasing_issues} rising, ${stats.decreasing_issues} falling`} color="#8b5cf6" />
          <StatCard icon={AlertTriangle} label="Critical Tickets" value={stats.critical_tickets.toLocaleString()} sub={`${stats.open_tickets} currently open`} color={COLORS.critical} />
          <StatCard icon={TrendingUp} label="Rising Issues" value={stats.increasing_issues} sub="Needs immediate attention" color={COLORS.increasing} />
          <StatCard icon={Bell} label="Anomalies" value={anomalies.length} sub="Unusual spike events" color="#f59e0b" />
          <StatCard icon={Users} label="Avg Satisfaction" value={`${stats.avg_satisfaction}/5`} sub="Across all tickets" color={COLORS.decreasing} />
        </div>

        {/* ─── Global Charts ─── */}
        <div style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr", gap: 14, marginBottom: 28 }}>
          {/* Monthly Volume */}
          <div style={{ background: COLORS.surface, borderRadius: 12, border: `1px solid ${COLORS.border}`, padding: "20px" }}>
            <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: "0 0 16px", textTransform: "uppercase", letterSpacing: "0.06em" }}>Monthly Ticket Volume</h3>
            <ResponsiveContainer width="100%" height={200}>
              <AreaChart data={stats.monthly_volume}>
                <defs>
                  <linearGradient id="volumeGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor={COLORS.accent} stopOpacity={0.2} />
                    <stop offset="100%" stopColor={COLORS.accent} stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke={COLORS.border} />
                <XAxis dataKey="month" tick={{ fill: COLORS.textDim, fontSize: 10 }} tickLine={false} axisLine={false} interval={2} />
                <YAxis tick={{ fill: COLORS.textDim, fontSize: 10 }} tickLine={false} axisLine={false} width={35} />
                <Tooltip contentStyle={{ background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 8, fontSize: 12 }} />
                <Area type="monotone" dataKey="count" stroke={COLORS.accent} fill="url(#volumeGrad)" strokeWidth={2} dot={false} />
              </AreaChart>
            </ResponsiveContainer>
          </div>

          {/* Type Distribution */}
          <div style={{ background: COLORS.surface, borderRadius: 12, border: `1px solid ${COLORS.border}`, padding: "20px" }}>
            <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: "0 0 16px", textTransform: "uppercase", letterSpacing: "0.06em" }}>Ticket Types</h3>
            <ResponsiveContainer width="100%" height={200}>
              <PieChart>
                <Pie
                  data={Object.entries(stats.type_distribution).map(([name, value]) => ({ name, value }))}
                  cx="50%" cy="50%" innerRadius={45} outerRadius={75} paddingAngle={3}
                  dataKey="value" strokeWidth={0}
                >
                  {Object.keys(stats.type_distribution).map((_, i) => (
                    <Cell key={i} fill={COLORS.chartColors[i % COLORS.chartColors.length]} />
                  ))}
                </Pie>
                <Tooltip contentStyle={{ background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 8, fontSize: 11 }} />
              </PieChart>
            </ResponsiveContainer>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginTop: 4 }}>
              {Object.entries(stats.type_distribution).map(([name], i) => (
                <span key={name} style={{ fontSize: 9, color: COLORS.textDim, display: "flex", alignItems: "center", gap: 3 }}>
                  <span style={{ width: 6, height: 6, borderRadius: 2, background: COLORS.chartColors[i] }} />
                  {name}
                </span>
              ))}
            </div>
          </div>

          {/* Priority Distribution */}
          <div style={{ background: COLORS.surface, borderRadius: 12, border: `1px solid ${COLORS.border}`, padding: "20px" }}>
            <h3 style={{ fontSize: 13, fontWeight: 600, color: COLORS.textMuted, margin: "0 0 16px", textTransform: "uppercase", letterSpacing: "0.06em" }}>Priority Levels</h3>
            <div style={{ display: "flex", flexDirection: "column", gap: 12, marginTop: 8 }}>
              {Object.entries(stats.priority_distribution).map(([name, value]) => {
                const pct = ((value / stats.total_tickets) * 100).toFixed(0);
                const color = PRIORITY_COLORS[name] || COLORS.textMuted;
                return (
                  <div key={name}>
                    <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 4 }}>
                      <span style={{ fontSize: 12, color: COLORS.textMuted }}>{name}</span>
                      <span style={{ fontSize: 12, fontWeight: 600, color: COLORS.text, fontFamily: "'JetBrains Mono', monospace" }}>{value} ({pct}%)</span>
                    </div>
                    <div style={{ width: "100%", height: 6, borderRadius: 3, background: COLORS.bg }}>
                      <div style={{ width: `${pct}%`, height: "100%", borderRadius: 3, background: color, transition: "width 0.5s ease" }} />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* ─── View Tabs + Filters ─── */}
        <div style={{
          display: "flex", justifyContent: "space-between", alignItems: "center",
          marginBottom: 18, flexWrap: "wrap", gap: 12,
        }}>
          <div style={{ display: "flex", gap: 4, background: COLORS.surface, borderRadius: 10, padding: 3, border: `1px solid ${COLORS.border}` }}>
            {[
              { id: "clusters", label: "Issue Clusters", icon: Layers },
              { id: "trends", label: "Trend Analysis", icon: Activity },
              { id: "anomalies", label: "Anomalies", icon: AlertTriangle },
            ].map(({ id, label, icon: Icon }) => (
              <button key={id} onClick={() => setView(id)} style={{
                padding: "8px 16px", borderRadius: 8, border: "none",
                background: view === id ? COLORS.accentDim : "transparent",
                color: view === id ? COLORS.accentLight : COLORS.textMuted,
                cursor: "pointer", fontSize: 12, fontWeight: 600,
                display: "flex", alignItems: "center", gap: 6, transition: "all 0.15s",
              }}>
                <Icon size={14} /> {label}
              </button>
            ))}
          </div>

          <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
            {/* Search */}
            <div style={{
              display: "flex", alignItems: "center", gap: 8, padding: "8px 14px",
              background: COLORS.surface, borderRadius: 8, border: `1px solid ${COLORS.border}`, width: 220,
            }}>
              <Search size={14} style={{ color: COLORS.textDim }} />
              <input
                placeholder="Search issues..."
                value={searchQuery}
                onChange={e => setSearchQuery(e.target.value)}
                style={{
                  background: "none", border: "none", outline: "none",
                  color: COLORS.text, fontSize: 12, width: "100%",
                }}
              />
            </div>

            {/* Trend Filter */}
            <div style={{ display: "flex", gap: 3, background: COLORS.surface, borderRadius: 8, padding: 3, border: `1px solid ${COLORS.border}` }}>
              {[
                { id: "all", label: "All" },
                { id: "increasing", label: "Rising" },
                { id: "stable", label: "Stable" },
                { id: "decreasing", label: "Falling" },
              ].map(({ id, label }) => (
                <button key={id} onClick={() => setFilter(id)} style={{
                  padding: "6px 12px", borderRadius: 6, border: "none",
                  background: filter === id ? COLORS.accentDim : "transparent",
                  color: filter === id ? COLORS.accentLight : COLORS.textDim,
                  cursor: "pointer", fontSize: 11, fontWeight: 600,
                  transition: "all 0.15s",
                }}>
                  {label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* ─── Cluster Cards View ─── */}
        {view === "clusters" && (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))", gap: 14 }}>
            {filteredClusters.map((cluster, i) => (
              <div
                key={cluster.id}
                onClick={() => setSelectedCluster(cluster)}
                style={{
                  background: COLORS.surface, borderRadius: 12, border: `1px solid ${COLORS.border}`,
                  padding: "20px", cursor: "pointer", transition: "all 0.2s",
                  animation: `fadeIn 0.3s ease ${i * 0.03}s both`,
                  position: "relative", overflow: "hidden",
                }}
                onMouseEnter={e => {
                  e.currentTarget.style.borderColor = COLORS.borderLight;
                  e.currentTarget.style.transform = "translateY(-2px)";
                  e.currentTarget.style.boxShadow = `0 8px 24px rgba(0,0,0,0.2)`;
                }}
                onMouseLeave={e => {
                  e.currentTarget.style.borderColor = COLORS.border;
                  e.currentTarget.style.transform = "translateY(0)";
                  e.currentTarget.style.boxShadow = "none";
                }}
              >
                {/* Severity indicator */}
                <div style={{
                  position: "absolute", top: 0, left: 0, right: 0, height: 3,
                  background: cluster.trend === "increasing" ? COLORS.increasing :
                    cluster.trend === "decreasing" ? COLORS.decreasing : COLORS.stable,
                  opacity: 0.6,
                }} />

                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12 }}>
                  <div>
                    <div style={{ fontSize: 10, color: COLORS.textDim, fontFamily: "'JetBrains Mono', monospace", marginBottom: 4 }}>
                      CLUSTER-{String(cluster.id).padStart(2, "0")} &bull; {cluster.top_type}
                    </div>
                    <h3 style={{ fontSize: 16, fontWeight: 700, color: COLORS.text }}>{cluster.name}</h3>
                  </div>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontSize: 22, fontWeight: 700, color: COLORS.text, fontFamily: "'JetBrains Mono', monospace", lineHeight: 1 }}>
                      {cluster.count}
                    </div>
                    <div style={{ fontSize: 10, color: COLORS.textDim }}>tickets</div>
                  </div>
                </div>

                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}>
                  <TrendBadge trend={cluster.trend} pctChange={cluster.pct_change} />
                  <MiniSparkline data={cluster.time_series} trend={cluster.trend} />
                </div>

                {/* Top terms */}
                <div style={{ display: "flex", flexWrap: "wrap", gap: 4, marginBottom: 12 }}>
                  {cluster.top_terms?.slice(0, 4).map((term, j) => (
                    <span key={j} style={{
                      padding: "2px 8px", borderRadius: 4, fontSize: 10,
                      background: COLORS.bg, color: COLORS.textDim, border: `1px solid ${COLORS.border}`,
                    }}>{term}</span>
                  ))}
                </div>

                {/* Products affected */}
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <div style={{ fontSize: 11, color: COLORS.textDim }}>
                    {cluster.top_products?.slice(0, 2).join(", ")}
                  </div>
                  <ChevronRight size={14} style={{ color: COLORS.textDim }} />
                </div>
              </div>
            ))}
          </div>
        )}

        {/* ─── Trend Analysis View ─── */}
        {view === "trends" && (
          <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
            {/* Rising Issues Alert */}
            {filteredClusters.filter(c => c.trend === "increasing").length > 0 && (
              <div style={{
                background: COLORS.increasingDim, borderRadius: 12, border: `1px solid rgba(239,68,68,0.3)`,
                padding: "18px 22px", display: "flex", alignItems: "center", gap: 14,
              }}>
                <AlertTriangle size={22} style={{ color: COLORS.increasing }} />
                <div>
                  <div style={{ fontSize: 14, fontWeight: 700, color: COLORS.increasing, marginBottom: 2 }}>
                    {filteredClusters.filter(c => c.trend === "increasing").length} Rising Issues Detected
                  </div>
                  <div style={{ fontSize: 12, color: COLORS.textMuted }}>
                    These issue clusters show increasing ticket volume and may need attention.
                  </div>
                </div>
              </div>
            )}

            {/* Trend Table */}
            <div style={{ background: COLORS.surface, borderRadius: 12, border: `1px solid ${COLORS.border}`, overflow: "hidden" }}>
              <div style={{
                display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr 1fr 160px",
                padding: "12px 20px", borderBottom: `1px solid ${COLORS.border}`,
                fontSize: 10, fontWeight: 600, color: COLORS.textDim,
                textTransform: "uppercase", letterSpacing: "0.06em",
              }}>
                <span>Issue</span><span>Total</span><span>Prev Window</span><span>Curr Window</span><span>Change</span><span>Trend</span>
              </div>
              {filteredClusters.map((cluster, i) => (
                <div
                  key={cluster.id}
                  onClick={() => setSelectedCluster(cluster)}
                  style={{
                    display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr 1fr 160px",
                    padding: "14px 20px", borderBottom: `1px solid ${COLORS.border}`,
                    cursor: "pointer", transition: "background 0.15s", alignItems: "center",
                    animation: `fadeIn 0.3s ease ${i * 0.02}s both`,
                  }}
                  onMouseEnter={e => e.currentTarget.style.background = COLORS.surfaceHover}
                  onMouseLeave={e => e.currentTarget.style.background = "transparent"}
                >
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 600, color: COLORS.text }}>{cluster.name}</div>
                    <div style={{ fontSize: 10, color: COLORS.textDim }}>{cluster.top_type}</div>
                  </div>
                  <span style={{ fontSize: 13, fontWeight: 600, fontFamily: "'JetBrains Mono', monospace" }}>{cluster.count}</span>
                  <span style={{ fontSize: 13, fontFamily: "'JetBrains Mono', monospace", color: COLORS.textMuted }}>{cluster.prev_window}</span>
                  <span style={{ fontSize: 13, fontFamily: "'JetBrains Mono', monospace", color: COLORS.text }}>{cluster.curr_window}</span>
                  <span style={{
                    fontSize: 13, fontWeight: 600, fontFamily: "'JetBrains Mono', monospace",
                    color: cluster.pct_change > 15 ? COLORS.increasing : cluster.pct_change < -15 ? COLORS.decreasing : COLORS.stable,
                    display: "flex", alignItems: "center", gap: 4,
                  }}>
                    {cluster.pct_change > 0 ? <ArrowUpRight size={12} /> : cluster.pct_change < 0 ? <ArrowDownRight size={12} /> : null}
                    {cluster.pct_change > 0 ? "+" : ""}{cluster.pct_change}%
                  </span>
                  <MiniSparkline data={cluster.time_series} trend={cluster.trend} width={140} height={28} />
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ─── Anomalies View ─── */}
        {view === "anomalies" && (
          <div>
            {anomalies.length === 0 ? (
              <div style={{ textAlign: "center", padding: 60, color: COLORS.textMuted }}>
                <Shield size={48} style={{ margin: "0 auto 16px", opacity: 0.5 }} />
                <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 4 }}>No anomalies detected</div>
                <div style={{ fontSize: 13 }}>All issue clusters are within normal parameters.</div>
              </div>
            ) : (
              <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                <div style={{
                  background: "rgba(245,158,11,0.08)", borderRadius: 12, border: `1px solid rgba(245,158,11,0.2)`,
                  padding: "16px 22px", marginBottom: 4,
                }}>
                  <div style={{ fontSize: 13, fontWeight: 600, color: "#f59e0b", marginBottom: 2 }}>
                    {anomalies.length} Anomalous Spike Events Detected
                  </div>
                  <div style={{ fontSize: 12, color: COLORS.textMuted }}>
                    Months where ticket volume exceeded 2 standard deviations above the cluster mean.
                  </div>
                </div>

                {anomalies.map((a, i) => (
                  <div key={i} style={{
                    background: COLORS.surface, borderRadius: 10, border: `1px solid ${COLORS.border}`,
                    padding: "16px 20px", display: "flex", justifyContent: "space-between", alignItems: "center",
                    animation: `fadeIn 0.3s ease ${i * 0.04}s both`,
                  }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
                      <div style={{
                        width: 40, height: 40, borderRadius: 10, background: "rgba(245,158,11,0.1)",
                        display: "flex", alignItems: "center", justifyContent: "center",
                      }}>
                        <Zap size={18} style={{ color: "#f59e0b" }} />
                      </div>
                      <div>
                        <div style={{ fontSize: 14, fontWeight: 600, color: COLORS.text }}>{a.cluster_name}</div>
                        <div style={{ fontSize: 11, color: COLORS.textDim }}>{a.month}</div>
                      </div>
                    </div>
                    <div style={{ display: "flex", gap: 24, alignItems: "center" }}>
                      <div style={{ textAlign: "center" }}>
                        <div style={{ fontSize: 10, color: COLORS.textDim }}>Actual</div>
                        <div style={{ fontSize: 18, fontWeight: 700, color: COLORS.increasing, fontFamily: "'JetBrains Mono', monospace" }}>{a.count}</div>
                      </div>
                      <div style={{ textAlign: "center" }}>
                        <div style={{ fontSize: 10, color: COLORS.textDim }}>Expected</div>
                        <div style={{ fontSize: 18, fontWeight: 700, color: COLORS.textMuted, fontFamily: "'JetBrains Mono', monospace" }}>{a.expected}</div>
                      </div>
                      <div style={{ textAlign: "center" }}>
                        <div style={{ fontSize: 10, color: COLORS.textDim }}>Threshold</div>
                        <div style={{ fontSize: 18, fontWeight: 700, color: "#f59e0b", fontFamily: "'JetBrains Mono', monospace" }}>{a.threshold}</div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* ─── Footer ─── */}
        <footer style={{
          marginTop: 40, padding: "20px 0", borderTop: `1px solid ${COLORS.border}`,
          display: "flex", justifyContent: "space-between", alignItems: "center",
          fontSize: 11, color: COLORS.textDim,
        }}>
          <span>Support Ticket Intelligence System &bull; TF-IDF + K-Means Clustering + Sliding Window Trend Detection</span>
          <span>Dataset: {stats.date_range.start} to {stats.date_range.end} &bull; {stats.total_clusters} clusters identified</span>
        </footer>
      </main>

      {/* ─── Slide-out Detail Panel ─── */}
      {selectedCluster && (
        <>
          <div
            style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.4)", zIndex: 999, backdropFilter: "blur(2px)" }}
            onClick={() => setSelectedCluster(null)}
          />
          <ClusterDetail cluster={selectedCluster} onClose={() => setSelectedCluster(null)} onCloseTicket={handleCloseTicket} />
        </>
      )}

      {/* ─── Ingest Modal ─── */}
      {showIngest && <IngestModal onClose={() => setShowIngest(false)} onSubmit={handleIngest} />}

      {/* ─── Toast Notification ─── */}
      {toast && (
        <div style={{
          position: "fixed", bottom: 24, left: "50%", transform: "translateX(-50%)",
          zIndex: 2000, animation: "fadeIn 0.2s ease",
        }}>
          <div style={{
            padding: "12px 24px", borderRadius: 10,
            background: toast.type === "warning" ? "rgba(234,179,8,0.15)" : "rgba(34,197,94,0.15)",
            border: `1px solid ${toast.type === "warning" ? "rgba(234,179,8,0.3)" : "rgba(34,197,94,0.3)"}`,
            color: toast.type === "warning" ? "#eab308" : "#22c55e",
            fontSize: 13, fontWeight: 600,
            backdropFilter: "blur(12px)",
            boxShadow: "0 8px 32px rgba(0,0,0,0.3)",
            display: "flex", alignItems: "center", gap: 8,
          }}>
            {toast.type === "warning" ? <AlertTriangle size={16} /> : <Zap size={16} />}
            {toast.message}
          </div>
        </div>
      )}
    </div>
  );
}